/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sise.gui;

import com.mycompany.sise.entity.Persona;
import com.mycompany.sise.entity.Producto;
import com.mycompany.sise.entity.Sucursal;
import com.mycompany.sise.logic.PersonaLogic;
import com.mycompany.sise.logic.ProductoLogic;
import com.mycompany.sise.logic.SucursalLogic;
import com.mycompany.sise.logic.VentaLogic;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jennifer
 */
public class IFrmReporteVentas extends javax.swing.JInternalFrame {

    SucursalLogic logicSuc = new SucursalLogic();
    ProductoLogic logicProd = new ProductoLogic();
    PersonaLogic logicPersona = new PersonaLogic();
    VentaLogic logicVENTA = new VentaLogic();
    
    public IFrmReporteVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        buttonSuc = new javax.swing.JRadioButton();
        buttonCliente = new javax.swing.JRadioButton();
        cboFiltro = new javax.swing.JComboBox<>();
        btnReporte = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "FILTRO"));

        buttonGroup1.add(buttonSuc);
        buttonSuc.setText("Sucursal");
        buttonSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSucActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonCliente);
        buttonCliente.setText("Cliente");
        buttonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(buttonSuc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCliente)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(cboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSuc)
                    .addComponent(buttonCliente))
                .addGap(28, 28, 28)
                .addComponent(cboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/imprimir (1).png"))); // NOI18N
        btnReporte.setText("REPORTE");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/salir.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporte)
                    .addComponent(btnSalir)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSucActionPerformed
        
        if(buttonSuc.isSelected()){
            try {
                logicSuc.imprimirCB(cboFiltro);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se puede llenar el Combo");
            }
        }
        
    }//GEN-LAST:event_buttonSucActionPerformed

    private void buttonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClienteActionPerformed
        
        if(buttonCliente.isSelected()){
            try {
                logicPersona.imprimirCB(cboFiltro);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se puede llenar el Combo");
            }
        }
    }//GEN-LAST:event_buttonClienteActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        
        try {
            
            if(buttonSuc.isSelected()){
            Sucursal obj = ((Sucursal)cboFiltro.getSelectedItem());
            int id_suc = obj.getId_sucursal();
            String nombre = obj.getNombre();
            String direccion = obj.getDireccion();
            String telefono = obj.getTelefono();
            int tipo = 1;
            
            HashMap<String, String> parametros = new HashMap<>();
            parametros.put("nombre", nombre);
            parametros.put("direccion", direccion);
            parametros.put("telefono", telefono);
            logicVENTA.imprimirReporte(logicVENTA.obtenerReportexSuc(id_suc), parametros, tipo);
            }else if(buttonCliente.isSelected()){
                
                Persona obj = ((Persona) cboFiltro.getSelectedItem());
                int id_persona = obj.getId_persona();
                String nombre = obj.getNombre();
                String apellidos = obj.getApellidos();
                String doc_identidad = obj.getDoc_identidad();
                String direccion = obj.getDireccion();
                int tipo = 2;
                
                HashMap<String, String> parametros = new HashMap<>();
                parametros.put("nombre", nombre);
                parametros.put("apellidos", apellidos);
                parametros.put("doc_identidad", doc_identidad);
                logicVENTA.imprimirReporte(logicVENTA.obtenerReportexCliente(id_persona), parametros, tipo);   
            }
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
        int valor = JOptionPane.showConfirmDialog(null, "Desea realmente Salir? ", "Sistema", JOptionPane.YES_NO_OPTION);
        if(valor == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JRadioButton buttonCliente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton buttonSuc;
    private javax.swing.JComboBox<String> cboFiltro;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
