/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sise.gui;

import com.mycompany.sise.entity.Inventario;
import com.mycompany.sise.entity.Producto;
import com.mycompany.sise.entity.Sucursal;
import com.mycompany.sise.logic.InventarioLogic;
import com.mycompany.sise.logic.ProductoLogic;
import com.mycompany.sise.logic.SucursalLogic;
import com.mycompany.sise.util.Helper;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author jennifer
 */
public class IFrmInventario extends javax.swing.JInternalFrame {

    InventarioLogic logic = null;
    SucursalLogic logicSucursal = null;
    ProductoLogic logicProducto = null;
    final ResourceBundle rb = ResourceBundle.getBundle("com.mycompany.sise.gui.mensajes");
    
    int pagina = 0;
    int contador = 0;
    int total = 0;
    
    public IFrmInventario() {
        initComponents();
        this.setTitle(rb.getString("titulo_inventario"));
        filtroComboSucursal();
        filtroComboProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboSucursal = new javax.swing.JComboBox<>();
        cboProducto = new javax.swing.JComboBox<>();
        txtStock = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cboPaginacion = new javax.swing.JComboBox<>();
        btnIzquierda = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204)), "DATOS"));

        jLabel1.setText("SUCURSAL:");

        jLabel2.setText("PRODUCTO:");

        jLabel3.setText("STOCK:");

        cboSucursal.setEditable(true);

        cboProducto.setEditable(true);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/new.png"))); // NOI18N
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboProducto, 0, 252, Short.MAX_VALUE)
                    .addComponent(cboSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnNew)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/listar.png"))); // NOI18N
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/agregar.png"))); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/modificar.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/imprimir (1).png"))); // NOI18N
        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/salir.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)), "BUSQUEDA"));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/buscar.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnBuscar)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbListaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbLista);

        jLabel8.setText("Reg. Pagina");

        cboPaginacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "2", "5", "10", "15" }));
        cboPaginacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPaginacionItemStateChanged(evt);
            }
        });

        btnIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/izquierda (2).png"))); // NOI18N
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });

        btnDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/derecha (2).png"))); // NOI18N
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnIzquierda)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDerecha)
                                    .addGap(125, 125, 125)
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboPaginacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboPaginacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDerecha)
                                    .addComponent(btnIzquierda)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        logic = new InventarioLogic();
        try {
            logic.imprimirTable(tbLista);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        logic = new InventarioLogic();
        
        if(txtStock.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No olvides ingresar el Stock");
        }else{
            Inventario objInventario = getInventario();

            try {
                Helper oHelperLogic = logic.insertarValidado(objInventario);
                if(oHelperLogic.getError()){
                    JOptionPane.showMessageDialog(null, oHelperLogic.getMensajeUsuario() );
                } else {
                    if(objInventario.getId_producto()>0 || objInventario.getId_sucursal()>0){
                        JOptionPane.showMessageDialog(null, rb.getString("mensaje_agregar"));
                    }

                    logic.imprimirTable(tbLista);
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex, "Sistema", JOptionPane.ERROR_MESSAGE);
            }

            limpiar();
        }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        logic = new InventarioLogic();

        try {
            logic.modificar(getInventario());
            JOptionPane.showMessageDialog(null, rb.getString("mensaje_modificar"));
            logic.imprimirTable(tbLista);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Sistema", JOptionPane.ERROR_MESSAGE);
        }

        limpiar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        logic = new InventarioLogic();

        try {
            logic.eliminar(getInventario());
            JOptionPane.showMessageDialog(null, rb.getString("mensaje_eliminar"));
            logic.imprimirTable(tbLista);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Sistema", JOptionPane.ERROR_MESSAGE);
        }

        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        int valor = JOptionPane.showConfirmDialog(null, "Desea realmente Salir? ", "Sistema", JOptionPane.YES_NO_OPTION);
        if(valor == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        logic = new InventarioLogic();
        try {
            logic.imprimirTable(tbLista, logic.busqueda(txtBusqueda.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cboPaginacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPaginacionItemStateChanged

        logic = new InventarioLogic();

        try {
            if(cboPaginacion.getSelectedIndex() >= 0){
                logic.imprimirTable(tbLista, logic.paginacion(0, Integer.parseInt(cboPaginacion.getSelectedItem()+"")));
            }else{
                logic.imprimirTable(tbLista);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cboPaginacionItemStateChanged

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed

        logic = new InventarioLogic();

        try {
            total = logic.cantidadRegistros();
            if(cboPaginacion.getSelectedIndex()> 0){
                int max = total/(Integer.parseInt(cboPaginacion.getSelectedItem() + ""));
                contador--;
                if(contador < 0) contador = 0;
                if(max >= contador){
                    pagina = (Integer.parseInt(cboPaginacion.getSelectedItem() + "")) * contador;
                    logic.imprimirTable(tbLista, logic.paginacion(pagina, Integer.parseInt(cboPaginacion.getSelectedItem() + "")));
                }else{
                    contador = 0;
                }
            }else{
                logic.imprimirTable(tbLista);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed

        logic = new InventarioLogic();
        try {
            total = logic.cantidadRegistros();
            if(cboPaginacion.getSelectedIndex()> 0){
                int max = total/(Integer.parseInt(cboPaginacion.getSelectedItem() + ""));
                contador++;
                if(max >= contador){
                    pagina = (Integer.parseInt(cboPaginacion.getSelectedItem() + "")) * contador;
                    logic.imprimirTable(tbLista, logic.paginacion(pagina, Integer.parseInt(cboPaginacion.getSelectedItem() + "")));
                }else{
                    contador = max;
                }
            }else{
                logic.imprimirTable(tbLista);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDerechaActionPerformed

    private void tbListaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaMouseReleased
        
        try {
            logicSucursal = new SucursalLogic();
            logicProducto = new ProductoLogic();
            int fila ;
            fila = tbLista.getSelectedRow();
            int id_Suc, id_Prod, stock;
        
            if(fila>=0){
                int i=0;
                id_Suc = Integer.parseInt(tbLista.getValueAt(fila, i++)+"");
                id_Prod = Integer.parseInt(tbLista.getValueAt(fila, i++)+"");
                stock = Integer.parseInt(tbLista.getValueAt(fila, i++)+"");

                btnAgregar.setEnabled(false);
                logicSucursal.selectItemByIDCombo(cboSucursal, id_Suc);
                logicProducto.selectItemByIDCombo(cboProducto, id_Prod);
                txtStock.setText(stock+"");
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Sistema", JOptionPane.ERROR_MESSAGE);
        }
               
    }//GEN-LAST:event_tbListaMouseReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
        this.cboPaginacion.setSelectedIndex(2);
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        limpiar();
        btnAgregar.setEnabled(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        
        logic = new InventarioLogic();
        try{
            HashMap<String, String> parametros = new HashMap<>();
            logic.imprimirReporte(parametros);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    Inventario getInventario(){
        
        return new Inventario(
            ((Sucursal)cboSucursal.getSelectedItem()).getId_sucursal(),
            ((Producto)cboProducto.getSelectedItem()).getId_producto(),
            Integer.parseInt(txtStock.getText())
            );
    }
    
    private void limpiar(){
        cboSucursal.setSelectedIndex(-1);
        cboProducto.setSelectedIndex(-1);
        txtStock.setText("");
    }

    private void llenarComboSucursal(){
        try {
            logicSucursal = new SucursalLogic();
            logicSucursal.imprimirCB(cboSucursal);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void llenarComboProducto(){
        try {
            logicProducto = new ProductoLogic();
            logicProducto.imprimirCB(cboProducto);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void filtroComboSucursal(){
  
        llenarComboSucursal();
    
        cboSucursal.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent evt){
                String filtro = cboSucursal.getEditor().getItem().toString();
                
                if(evt.getKeyCode()>=65 && evt.getKeyCode()<=90 || evt.getKeyCode() >= 96 && evt.getKeyCode() <= 105 || evt.getKeyCode() ==8){
                    try {
                        logicSucursal = new SucursalLogic();
                        cboSucursal.setModel(logicSucursal.getListaSucursal(filtro));
                        if(cboSucursal.getItemCount()>0){
                            cboSucursal.showPopup();
                            if(evt.getKeyCode()!=8){
                                ((JTextComponent)cboSucursal.getEditor().getEditorComponent()).select(filtro.length(),cboSucursal.getEditor().getItem().toString().length());
                            }else{
                                cboSucursal.getEditor().setItem(filtro);
                            }
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex, "Sistema", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
    }
    
    private void filtroComboProducto(){
  
        llenarComboProducto();
    
        cboProducto.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent evt){
                String filtro = cboProducto.getEditor().getItem().toString();
                
                if(evt.getKeyCode()>=65 && evt.getKeyCode()<=90 || evt.getKeyCode() >= 96 && evt.getKeyCode() <= 105 || evt.getKeyCode() ==8){
                    try {
                        logicProducto = new ProductoLogic();
                        cboProducto.setModel(logicProducto.getListaProducto(filtro));
                        if(cboProducto.getItemCount()>0){
                            cboProducto.showPopup();
                            if(evt.getKeyCode()!=8){
                                ((JTextComponent)cboProducto.getEditor().getEditorComponent()).select(filtro.length(),cboProducto.getEditor().getItem().toString().length());
                            }else{
                                cboProducto.getEditor().setItem(filtro);
                            }
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex, "Sistema", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboPaginacion;
    private javax.swing.JComboBox<String> cboProducto;
    private javax.swing.JComboBox<String> cboSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
