/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sise.gui;
import com.mycompany.sise.entity.Descuento;
import com.mycompany.sise.entity.Producto;
import com.mycompany.sise.entity.ProductoDescuento;
import com.mycompany.sise.logic.DescuentoLogic;
import com.mycompany.sise.logic.ProductoDescuentoLogic;
import com.mycompany.sise.logic.ProductoLogic;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

/**
 *
 * @author jennifer
 */
public class IFrmProductoDescuento extends javax.swing.JInternalFrame {

    ProductoDescuentoLogic logic = null;
    ProductoLogic logicProducto = null;
    DescuentoLogic logicDescuento = null;
    
    final ResourceBundle rb = ResourceBundle.getBundle("com.mycompany.sise.gui.mensajes");
    
    int pagina = 0;
    int contador = 0;
    int total = 0;
    
    public IFrmProductoDescuento() {
        initComponents();
        this.setTitle(rb.getString("titulo_productoDescuento"));
        filtroComboProducto();
        filtroComboDescuento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboProducto = new javax.swing.JComboBox<>();
        cboDescuento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        dtpFechaInicio = new org.jdatepicker.JDatePicker();
        dtpFechaFin = new org.jdatepicker.JDatePicker();
        btnListar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cboPaginacion = new javax.swing.JComboBox<>();
        btnIzquierda = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204)), "DATOS"));

        jLabel1.setText("PRODUCTO:");

        jLabel2.setText("DESCUENTO:");

        jLabel3.setText("FECHA DE INICIO:");

        cboProducto.setEditable(true);

        cboDescuento.setEditable(true);

        jLabel4.setText("FECHA DE FIN:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtpFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtpFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtpFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtpFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/listar.png"))); // NOI18N
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/agregar.png"))); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/modificar.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/imprimir (1).png"))); // NOI18N
        btnImprimir.setText("IMPRIMIR");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/salir.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)), "BUSQUEDA"));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/buscar.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnBuscar)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbListaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbLista);

        jLabel8.setText("Reg. Pagina");

        cboPaginacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "2", "5", "10", "15" }));
        cboPaginacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPaginacionItemStateChanged(evt);
            }
        });

        btnIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/izquierda (2).png"))); // NOI18N
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });

        btnDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/sise/gui/resources/derecha (2).png"))); // NOI18N
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnIzquierda)
                                .addGap(18, 18, 18)
                                .addComponent(btnDerecha)
                                .addGap(117, 117, 117)
                                .addComponent(jLabel8)
                                .addGap(27, 27, 27)
                                .addComponent(cboPaginacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIzquierda)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDerecha)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboPaginacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        logic = new ProductoDescuentoLogic();
        try {
            logic.imprimirTable(tbLista);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        logic = new ProductoDescuentoLogic();
       
        ProductoDescuento objProdDesc = getProdDesc();

        try {
            logic.insertar(objProdDesc);
            logic.imprimirTable(tbLista);
            JOptionPane.showMessageDialog(null, rb.getString("mensaje_agregar"));
            limpiar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        limpiar();
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        logic = new ProductoDescuentoLogic();

        try {
            logic.modificar(getProdDesc());
            JOptionPane.showMessageDialog(null, rb.getString("mensaje_modificar"));
            logic.imprimirTable(tbLista);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Sistema", JOptionPane.ERROR_MESSAGE);
        }

        limpiar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        logic = new ProductoDescuentoLogic();

        try {
            logic.eliminar(getProdDesc());
            JOptionPane.showMessageDialog(null, rb.getString("mensaje_eliminar"));
            logic.imprimirTable(tbLista);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Sistema", JOptionPane.ERROR_MESSAGE);
        }

        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        int valor = JOptionPane.showConfirmDialog(null, "Desea realmente Salir? ", "Sistema", JOptionPane.YES_NO_OPTION);
        if(valor == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        logic = new ProductoDescuentoLogic();
        try {
            logic.imprimirTable(tbLista, logic.busqueda(txtBusqueda.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cboPaginacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPaginacionItemStateChanged

        logic = new ProductoDescuentoLogic();

        try {
            if(cboPaginacion.getSelectedIndex() >= 0){
                logic.imprimirTable(tbLista, logic.paginacion(0, Integer.parseInt(cboPaginacion.getSelectedItem()+"")));
            }else{
                logic.imprimirTable(tbLista);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cboPaginacionItemStateChanged

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed

        logic = new ProductoDescuentoLogic();

        try {
            total = logic.cantidadRegistros();
            if(cboPaginacion.getSelectedIndex()> 0){
                int max = total/(Integer.parseInt(cboPaginacion.getSelectedItem() + ""));
                contador--;
                if(contador < 0) contador = 0;
                if(max >= contador){
                    pagina = (Integer.parseInt(cboPaginacion.getSelectedItem() + "")) * contador;
                    logic.imprimirTable(tbLista, logic.paginacion(pagina, Integer.parseInt(cboPaginacion.getSelectedItem() + "")));
                }else{
                    contador = 0;
                }
            }else{
                logic.imprimirTable(tbLista);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed

        logic = new ProductoDescuentoLogic();
        try {
            total = logic.cantidadRegistros();
            if(cboPaginacion.getSelectedIndex()> 0){
                int max = total/(Integer.parseInt(cboPaginacion.getSelectedItem() + ""));
                contador++;
                if(max >= contador){
                    pagina = (Integer.parseInt(cboPaginacion.getSelectedItem() + "")) * contador;
                    logic.imprimirTable(tbLista, logic.paginacion(pagina, Integer.parseInt(cboPaginacion.getSelectedItem() + "")));
                }else{
                    contador = max;
                }
            }else{
                logic.imprimirTable(tbLista);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDerechaActionPerformed

    private void tbListaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaMouseReleased
        
        try {
            logicProducto = new ProductoLogic();
            logicDescuento = new DescuentoLogic();
            int fila ;
            fila = tbLista.getSelectedRow();
            int id_Prod, id_Desc;
            LocalDate fechaInicio;
            LocalDate fechaFin;
        
            if(fila>=0){
                int i=0;
                id_Prod = Integer.parseInt(tbLista.getValueAt(fila, i++)+"");
                id_Desc = Integer.parseInt(tbLista.getValueAt(fila, i++)+"");
                fechaInicio = LocalDate.parse(tbLista.getValueAt(fila, i++)+"");
                fechaFin = LocalDate.parse(tbLista.getValueAt(fila, i++)+"");

                logicProducto.selectItemByIDCombo(cboProducto, id_Prod);
                logicDescuento.selectItemByIDCombo(cboDescuento, id_Desc);
                dtpFechaInicio.getModel().setDate(
                    fechaInicio.getYear(), //año
                    fechaInicio.getMonthValue()-1, //mes
                    fechaInicio.getDayOfMonth()); // dia
                dtpFechaInicio.getModel().setSelected(true);
                dtpFechaFin.getModel().setDate(
                    fechaFin.getYear(), //año
                    fechaFin.getMonthValue()-1, //mes
                    fechaFin.getDayOfMonth()); // dia
                dtpFechaFin.getModel().setSelected(true);
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Sistema", JOptionPane.ERROR_MESSAGE);
        }
               
    }//GEN-LAST:event_tbListaMouseReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
        this.cboPaginacion.setSelectedIndex(1);
    }//GEN-LAST:event_formInternalFrameOpened

    ProductoDescuento getProdDesc(){
        
        int anioI, mesI, diaI, anioF, mesF, diaF;
        anioI = dtpFechaInicio.getModel().getYear();
        mesI = dtpFechaInicio.getModel().getMonth()+1;
        diaI = dtpFechaInicio.getModel().getDay();
        anioF = dtpFechaFin.getModel().getYear();
        mesF = dtpFechaFin.getModel().getMonth()+1;
        diaF = dtpFechaFin.getModel().getDay();
        
        return new ProductoDescuento(
            ((Producto)cboProducto.getSelectedItem()).getId_producto(),
            ((Descuento)cboDescuento.getSelectedItem()).getId_descuento(),
            LocalDate.of(anioI, mesI, diaI),
            LocalDate.of(anioF, mesF, diaF)
            );
        
    }
    
    private void limpiar(){
        cboProducto.setSelectedIndex(-1);
        cboDescuento.setSelectedIndex(-1);
        dtpFechaInicio.getModel().setDate(
                    LocalDate.now().getYear(), //año
                    LocalDate.now().getMonthValue()-1, //mes
                    LocalDate.now().getDayOfMonth()); // dia
        dtpFechaInicio.getModel().setSelected(true);
        dtpFechaFin.getModel().setDate(
                    LocalDate.now().getYear(), //año
                    LocalDate.now().getMonthValue()-1, //mes
                    LocalDate.now().getDayOfMonth()); // dia
        dtpFechaFin.getModel().setSelected(true);
    }

    private void llenarComboProducto(){
        try {
            logicProducto = new ProductoLogic();
            logicProducto.imprimirCB(cboProducto);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void llenarComboDescuento(){
        try {
            logicDescuento = new DescuentoLogic();
            logicDescuento.imprimirCB(cboDescuento);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void filtroComboProducto(){
  
        llenarComboProducto();
    
        cboProducto.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent evt){
                String filtro = cboProducto.getEditor().getItem().toString();
                
                if(evt.getKeyCode()>=65 && evt.getKeyCode()<=90 || evt.getKeyCode() >= 96 && evt.getKeyCode() <= 105 || evt.getKeyCode() ==8){
                    try {
                        logicProducto = new ProductoLogic();
                        cboProducto.setModel(logicProducto.getListaProducto(filtro));
                        if(cboProducto.getItemCount()>0){
                            cboProducto.showPopup();
                            if(evt.getKeyCode()!=8){
                                ((JTextComponent)cboProducto.getEditor().getEditorComponent()).select(filtro.length(),cboProducto.getEditor().getItem().toString().length());
                            }else{
                                cboProducto.getEditor().setItem(filtro);
                            }
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex, "Sistema", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
    }
    
    
    private void filtroComboDescuento(){
  
        llenarComboDescuento();
    
        cboDescuento.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent evt){
                String filtro = cboDescuento.getEditor().getItem().toString();
                
                if(evt.getKeyCode()>=65 && evt.getKeyCode()<=90 || evt.getKeyCode() >= 96 && evt.getKeyCode() <= 105 || evt.getKeyCode() ==8){
                    try {
                        logicDescuento = new DescuentoLogic();
                        cboDescuento.setModel(logicDescuento.getListaDescuento(filtro));
                        if(cboDescuento.getItemCount()>0){
                            cboDescuento.showPopup();
                            if(evt.getKeyCode()!=8){
                                ((JTextComponent)cboDescuento.getEditor().getEditorComponent()).select(filtro.length(),cboDescuento.getEditor().getItem().toString().length());
                            }else{
                                cboDescuento.getEditor().setItem(filtro);
                            }
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex, "Sistema", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboDescuento;
    private javax.swing.JComboBox<String> cboPaginacion;
    private javax.swing.JComboBox<String> cboProducto;
    private org.jdatepicker.JDatePicker dtpFechaFin;
    private org.jdatepicker.JDatePicker dtpFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
